"""initial erik schema

Revision ID: 0c802611e4f3
Revises: 
Create Date: 2026-07-18 23:06:52.857515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c802611e4f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('label_ru', sa.String(length=60), nullable=True),
    sa.Column('label_kz', sa.String(length=60), nullable=True),
    sa.Column('glyph', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.String(length=3), nullable=False),
    sa.Column('name_ru', sa.String(length=60), nullable=True),
    sa.Column('name_kz', sa.String(length=60), nullable=True),
    sa.Column('map_x', sa.Float(), nullable=True),
    sa.Column('map_y', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('base_yes', sa.Float(), nullable=True),
    sa.Column('base_maybe', sa.Float(), nullable=True),
    sa.Column('base_no', sa.Float(), nullable=True),
    sa.Column('p_min', sa.Float(), nullable=True),
    sa.Column('p_max', sa.Float(), nullable=True),
    sa.Column('sigma_k', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('label_ru', sa.String(length=60), nullable=True),
    sa.Column('label_kz', sa.String(length=60), nullable=True),
    sa.Column('tint', sa.String(length=9), nullable=True),
    sa.Column('ink', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=8), nullable=True),
    sa.Column('city_id', sa.String(length=3), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('hours_total', sa.Integer(), nullable=True),
    sa.Column('events_attended', sa.Integer(), nullable=True),
    sa.Column('trust_came', sa.Integer(), nullable=True),
    sa.Column('trust_total', sa.Integer(), nullable=True),
    sa.Column('reliability', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reset_token'),
    sa.UniqueConstraint('verification_token')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_nickname'), ['nickname'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)

    op.create_table('badge_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.String(length=16), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_badge_award')
    )
    with op.batch_alter_table('badge_awards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badge_awards_user_id'), ['user_id'], unique=False)

    op.create_table('conversation_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_convo_member')
    )
    with op.batch_alter_table('conversation_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_members_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_members_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('text_ru', sa.String(length=300), nullable=True),
    sa.Column('text_kz', sa.String(length=300), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notif_user_read', ['user_id', 'read', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('cat', sa.String(length=16), nullable=True),
    sa.Column('city_id', sa.String(length=3), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('about_ru', sa.Text(), nullable=True),
    sa.Column('about_kz', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cat'], ['themes.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=12), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('text_ru', sa.String(length=300), nullable=True),
    sa.Column('text_kz', sa.String(length=300), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charity_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=200), nullable=True),
    sa.Column('title_kz', sa.String(length=200), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.String(length=3), nullable=True),
    sa.Column('kind', sa.String(length=6), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('goal', sa.Integer(), nullable=True),
    sa.Column('raised', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_follow')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follows_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_user_id'), ['user_id'], unique=False)

    op.create_table('gatherings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.String(length=3), nullable=True),
    sa.Column('theme', sa.String(length=16), nullable=True),
    sa.Column('title_ru', sa.String(length=200), nullable=True),
    sa.Column('title_kz', sa.String(length=200), nullable=True),
    sa.Column('place_ru', sa.String(length=200), nullable=True),
    sa.Column('place_kz', sa.String(length=200), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('format', sa.String(length=4), nullable=True),
    sa.Column('needed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.Column('ctx', sa.Float(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('going_cache', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['theme'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gatherings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gatherings_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_gatherings_owner_id'), ['owner_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gathering_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=5), nullable=True),
    sa.Column('presence', sa.String(length=6), nullable=True),
    sa.Column('hours_credited', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gathering_id'], ['gatherings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gathering_id', name='uq_attendance')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_gathering_id'), ['gathering_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_user_id'), ['user_id'], unique=False)

    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charity_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_charity_id'), ['charity_id'], unique=False)

    op.create_table('gathering_coordinators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gathering_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['gathering_id'], ['gatherings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gathering_id', 'user_id', name='uq_gcoord')
    )
    with op.batch_alter_table('gathering_coordinators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gathering_coordinators_gathering_id'), ['gathering_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gathering_coordinators_user_id'), ['user_id'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gathering_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('answer', sa.String(length=5), nullable=True),
    sa.Column('presence', sa.String(length=6), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=True),
    sa.Column('client_mark_id', sa.String(length=64), nullable=True),
    sa.Column('hist_total_at_rsvp', sa.Integer(), nullable=True),
    sa.Column('hist_came_at_rsvp', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gathering_id'], ['gatherings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gathering_id', 'user_id', name='uq_participant_user')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index('ix_participant_poll', ['gathering_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_client_mark_id'), ['client_mark_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_gathering_id'), ['gathering_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_user_id'), ['user_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gathering_id', sa.Integer(), nullable=True),
    sa.Column('sent_by_id', sa.Integer(), nullable=True),
    sa.Column('audience', sa.String(length=5), nullable=True),
    sa.Column('text_ru', sa.String(length=300), nullable=True),
    sa.Column('text_kz', sa.String(length=300), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gathering_id'], ['gatherings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_gathering_id'), ['gathering_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_gathering_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_participants_gathering_id'))
        batch_op.drop_index(batch_op.f('ix_participants_client_mark_id'))
        batch_op.drop_index('ix_participant_poll')

    op.drop_table('participants')
    with op.batch_alter_table('gathering_coordinators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gathering_coordinators_user_id'))
        batch_op.drop_index(batch_op.f('ix_gathering_coordinators_gathering_id'))

    op.drop_table('gathering_coordinators')
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_charity_id'))

    op.drop_table('donations')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_gathering_id'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('gatherings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gatherings_owner_id'))
        batch_op.drop_index(batch_op.f('ix_gatherings_code'))

    op.drop_table('gatherings')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_user_id'))
        batch_op.drop_index(batch_op.f('ix_follows_org_id'))

    op.drop_table('follows')
    op.drop_table('charity_requests')
    op.drop_table('reports')
    op.drop_table('orgs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index('ix_notif_user_read')

    op.drop_table('notifications')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversation_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_members_conversation_id'))

    op.drop_table('conversation_members')
    with op.batch_alter_table('badge_awards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badge_awards_user_id'))

    op.drop_table('badge_awards')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_nickname'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_device_id'))

    op.drop_table('users')
    op.drop_table('themes')
    op.drop_table('forecast_params')
    op.drop_table('conversations')
    op.drop_table('cities')
    op.drop_table('badges')
    # ### end Alembic commands ###
